Update 2000-01-01-viewport-size.md
---------------------------------- file change #1-------------------------------------------------------------
phantom.args is undefined:
TypeError: undefined is not an object (evaluating 'phantom.args.length')

Solution :

 var  system = require('system');

---------------------------------- file change #2-------------------------------------------------------------
After implementing the file change #1 > 
1- variables should be updated accordingly (use object  "system.args" instead of "phantom.args")
2- the array values should  start from 1 (0 is the current "viewport.js" script file):
address = system.args[1];
output = system.args[2];
sizeX = system.args[3];
sizeY = system.args[4];
--------instead of:---------
address = system.args[0];
output = system.args[1];
sizeX = system.args[2];
sizeY = system.args[3];
-----------------------------